---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
