---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    commit-message:
      include: scope
      prefix: "feat"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "conventional-changelog-conventionalcommits"
        versions: [ ">=6.0.0" ]
    open-pull-requests-limit: 5
    commit-message:
      include: scope
      prefix: "feat"
