---
name: Codeowners

on:
  - pull_request

jobs:
  validate:
    runs-on: linux

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
        env:
          ImageOS: ubuntu20
      - name: Install codeowners checker
        shell: bash
        run: gem install codeowners-checker
      - name: Run codeowners checker
        shell: bash
        run: codeowners-checker check --no-interactive .
