---
name: Notify PRs

on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Notify PRs
        uses: nrkno/github-action-sematic-release@e55264c861b15bfa021daadeab0888a851a8f263
        with:
          subcommand: notify
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          SEMREL_TAG: ${{ github.event.release.tag_name }}
          SEMREL_VERSION: ${{ github.event.release.name }}
          SEMREL_RELEASE_URL: ${{ github.event.release.html_url }}
